KAMANJA-411 'add' code complete
All the code is there for the AddAdapterMessageBinding.  Builds.

Testing still to do. The easy installer doesn't have enough heap space in its configuration for java 1.7 evidently.
I am getting this:

[error] uncaught exception during compilation: java.lang.OutOfMemoryError

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
        at sbt.Execute.next$1(Execute.scala:83)
        at sbt.Execute.processAll(Execute.scala:86)

This happened :

[error]      while compiling: /home/rich/github/dev/1.4.0.Base/kamanja/trunk/Storage/HBase/src/main/scala/com/ligadata/keyvaluestore/HBaseAdapter.scala